gui:
  theme:
    activeBorderColor:
      - '#88c0d0' # Nord Frost Blue
      - bold
    inactiveBorderColor:
      - '#4c566a' # Nord Polar Night 3
    optionsTextColor:
      - '#81a1c1' # Nord Frost Arctic
    selectedLineBgColor:
      - '#3b4252' # Nord Polar Night 1
    cherryPickedCommitBgColor:
      - '#434c5e' # Nord Polar Night 2
    cherryPickedCommitFgColor:
      - '#88c0d0' # Nord Frost Blue
    unstagedChangesColor:
      - '#bf616a' # Nord Aurora Red
    defaultSideSize: 0.4
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
os:
  editCommand: 'nvim'
