db_path = "~/.local/share/atuin/history.db"
search_mode = "fuzzy"
filter_mode = "global"
style = "compact"
inline_height = 15
show_preview = true
enter_accept = true
secrets_filter = true
workspaces = false
show_help = true
show_tabs = true
auto_sync = false
update_check = false
store_failed = true
strip_trailing_whitespace = true

[stats]
common_subcommands = ["git", "docker", "kubectl", "npm", "pnpm", "yarn", "cargo", "systemctl", "brew", "go", "nix"]
common_prefix = ["sudo"]

[sync]
records = true
